[package]
name = "gdl90codec"
version = "0.1.0"
authors = ["Red Hot Gekko <redhotgekko@outlook.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
deku = "0.19.0"
enum-ordinalize = "4.3.0"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"